export type Vehicle = {
  id: string;
  title: string;
  image: string;
  kms: string;
  fuel: string;
  owner: string;
  transmissionType: string;
  rc_availability: boolean;
  repo_date: string;
  regs_no: string;
  region: string;
  has_bidded: boolean;
  bidding_status: 'Winning' | 'Losing' | null;
  isFavorite?: boolean;
  endTime?: string;
  manager_name: string;
  manager_phone: string;
  hasBid?: boolean;
  bid_created_dttm?: string;
  user_bid_amount?: string;
  status?: string;
  yard_contact_person_name?: string | null;
  contact_person_contact_no?: string | null;
  yard_address?: string | null;
  yard_address_zip?: string | null;
  yard_city?: string | null;
  yard_state?: string | null;
};