// AUTO-GENERATED, DO NOT EDIT

export const images: Record<string, any> = {
  "commercial": require("../assets/data-files/case_option/commercial.png"),
  "fireloss": require("../assets/data-files/case_option/fireloss.png"),
  "flood": require("../assets/data-files/case_option/flood.png"),
  "luxury": require("../assets/data-files/case_option/luxury.png"),
  "pan": require("../assets/data-files/case_option/pan.png"),
  "partialsalvage": require("../assets/data-files/case_option/partialsalvage.png"),
  "readytolift": require("../assets/data-files/case_option/readytolift.png"),
  "theft": require("../assets/data-files/case_option/theft.png"),
  "transit": require("../assets/data-files/case_option/transit.png"),
  "east": require("../assets/data-files/region/east.png"),
  "north": require("../assets/data-files/region/north.png"),
  "south": require("../assets/data-files/region/south.png"),
  "west": require("../assets/data-files/region/west.png"),
  "1": require("../assets/data-files/vehicles/1/1.jpg"),
  "2": require("../assets/data-files/vehicles/1/2.jpg"),
  "3": require("../assets/data-files/vehicles/1/3.jpg"),
  "4": require("../assets/data-files/vehicles/1/4.jpg"),
  "5": require("../assets/data-files/vehicles/1/5.jpg"),
  "1": require("../assets/data-files/vehicles/2/1.jpg"),
  "2": require("../assets/data-files/vehicles/2/2.jpg"),
  "3": require("../assets/data-files/vehicles/2/3.jpg"),
  "4": require("../assets/data-files/vehicles/2/4.jpg"),
  "5": require("../assets/data-files/vehicles/2/5.jpg"),
  "1": require("../assets/data-files/vehicles/3/1.jpg"),
  "2": require("../assets/data-files/vehicles/3/2.jpg"),
  "3": require("../assets/data-files/vehicles/3/3.jpg"),
  "4": require("../assets/data-files/vehicles/3/4.jpg"),
  "5": require("../assets/data-files/vehicles/3/5.jpg"),
  "1": require("../assets/data-files/vehicles/4/1.jpg"),
  "2": require("../assets/data-files/vehicles/4/2.jpg"),
  "3": require("../assets/data-files/vehicles/4/3.jpg"),
  "4": require("../assets/data-files/vehicles/4/4.jpg"),
  "5": require("../assets/data-files/vehicles/4/5.jpg"),
  "1": require("../assets/data-files/vehicles/5/1.jpg"),
  "2": require("../assets/data-files/vehicles/5/2.jpg"),
  "3": require("../assets/data-files/vehicles/5/3.jpg"),
  "4": require("../assets/data-files/vehicles/5/4.jpg"),
  "5": require("../assets/data-files/vehicles/5/5.jpg"),
};
