// AUTO-GENERATED, DO NOT EDIT

export const images: Record<string, any> = {
  "commercial": require("../assets/data-files/case_option/commercial.png"),
  "fireloss": require("../assets/data-files/case_option/fireloss.png"),
  "flood": require("../assets/data-files/case_option/flood.png"),
  "luxury": require("../assets/data-files/case_option/luxury.png"),
  "pan": require("../assets/data-files/case_option/pan.png"),
  "partialsalvage": require("../assets/data-files/case_option/partialsalvage.png"),
  "readytolift": require("../assets/data-files/case_option/readytolift.png"),
  "theft": require("../assets/data-files/case_option/theft.png"),
  "transit": require("../assets/data-files/case_option/transit.png"),
  "east": require("../assets/data-files/region/east.png"),
  "north": require("../assets/data-files/region/north.png"),
  "south": require("../assets/data-files/region/south.png"),
  "west": require("../assets/data-files/region/west.png"),
  "vehicle-1-1": require("../assets/data-files/vehicle/1/1.jpg"),
  "vehicle-1-2": require("../assets/data-files/vehicle/1/2.jpg"),
  "vehicle-1-3": require("../assets/data-files/vehicle/1/3.jpg"),
  "vehicle-1-4": require("../assets/data-files/vehicle/1/4.jpg"),
  "vehicle-1-5": require("../assets/data-files/vehicle/1/5.jpg"),
  "vehicle-2-1": require("../assets/data-files/vehicle/2/1.jpg"),
  "vehicle-2-2": require("../assets/data-files/vehicle/2/2.jpg"),
  "vehicle-2-3": require("../assets/data-files/vehicle/2/3.jpg"),
  "vehicle-2-4": require("../assets/data-files/vehicle/2/4.jpg"),
  "vehicle-2-5": require("../assets/data-files/vehicle/2/5.jpg"),
  "vehicle-3-1": require("../assets/data-files/vehicle/3/1.jpg"),
  "vehicle-3-2": require("../assets/data-files/vehicle/3/2.jpg"),
  "vehicle-3-3": require("../assets/data-files/vehicle/3/3.jpg"),
  "vehicle-3-4": require("../assets/data-files/vehicle/3/4.jpg"),
  "vehicle-3-5": require("../assets/data-files/vehicle/3/5.jpg"),
  "vehicle-4-1": require("../assets/data-files/vehicle/4/1.jpg"),
  "vehicle-4-2": require("../assets/data-files/vehicle/4/2.jpg"),
  "vehicle-4-3": require("../assets/data-files/vehicle/4/3.jpg"),
  "vehicle-4-4": require("../assets/data-files/vehicle/4/4.jpg"),
  "vehicle-4-5": require("../assets/data-files/vehicle/4/5.jpg"),
  "vehicle-5-1": require("../assets/data-files/vehicle/5/1.jpg"),
  "vehicle-5-2": require("../assets/data-files/vehicle/5/2.jpg"),
  "vehicle-5-3": require("../assets/data-files/vehicle/5/3.jpg"),
  "vehicle-5-4": require("../assets/data-files/vehicle/5/4.jpg"),
  "vehicle-5-5": require("../assets/data-files/vehicle/5/5.jpg"),
};
